# -------------------------------------------------------------------------------- 
# aws-vpc.tf.tmpl
#
# DO NOT EDIT THIS FILE!!!! It is regenerated whenever `create-project` is run.
# Any change you make will be lost. If you need to change it, update the template
# for this file, located in <terraform-talk>/modules/python/terraform/templates
#
# Kevin Cureton 2023 covered by the gpl-3.0
# -------------------------------------------------------------------------------- 

module "aws-vpc-vpc" {
  source = "../../../modules/terraform/aws-vpc-v1"

  project_name      = "vpc"
  deployment_env    = "dev"
  deployment_region = "us-west-2"
}
